### PR TITLE
Fixed another incorrect check

### PR DESCRIPTION
**Pull request by frenck**
# Proposed Changes

Another one 😢 

#287

### CODE REVIEW

**Comment by hioctane61** [comment]
dude, you do a great job. Could happen to anyone. Keep up the good work.

**Comment by frenck** [comment]
Thanks, @hioctane61 ❤️

**Comment by ErikCoen** [comment]
I have lost all the files inside the folder /homeassistant/appdaemon after updating appdaemon to 0.15.2!

**Comment by frenck** [comment]
@ErikCoen correct, they moved, as per release notes.

**Comment by ErikCoen** [comment]
I see it is moved to /addon_configs/a0d7b954_appdaemon/

but I got the error message:

s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[22:20:13] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
ERROR Error loading secrets file: /config/secrets.yaml
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[22:20:19] INFO: Service AppDaemon exited with code 1 (by signal 0)

**Comment by ErikCoen** [comment]
It is resolved as mentioned in the release not:

appdaemon.yaml changed to:
secrets: /homeassistant/secrets.yaml

Thanks in advantage!

**Comment by saschaludwig** [comment]
> It is resolved as mentioned in the release not:
> appdaemon.yaml changed to: secrets: /homeassistant/secrets.yaml
> Thanks in advantage!

That did the trick!
Changing the path in appdaemon.yaml to:
`secrets: /homeassistant/secrets.yaml`

Because the appdaemon directory moved one level up and into `/addon_configs/`, how can I edit the config files from Studio Code Server? I only have /config/ exposed there by default. Does anyone here have a hint on how to change this?

**Comment by davisrg** [comment]
I had to restore from backup after updating AppDaemon to 15.2.  I lost the ability to edit my dashboard from HA File Editor because the path is too high level for File Editor to access.  I tried configuring ssh but had issues connecting (still looking into why).

**Comment by frenck** [comment]
See #287

**Pull request merged**
